<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

/** @var \Ubermanu\EsImportMap\Helper\Data $helper */
$helper = $this->helper(\Ubermanu\EsImportMap\Helper\Data::class);

$content = \Magento\Framework\Serialize\JsonConverter::convert($helper->getMagentoImportMap());
echo $secureRenderer->renderTag('script', ['type' => 'importmap'], $content, false);
