<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 */

$helper = $this->helper(\Ubermanu\EsImportMap\Helper\Data::class);
$content = \Magento\Framework\Serialize\JsonConverter::convert($helper->getMagentoImportMap());

echo $secureRenderer->renderTag('script', ['type' => 'importmap'], $content, false);
